export const COMPAT_PRIMARY_KEYS = Object.freeze({
  admin_users: ['id'],
  app_colors: ['id'],
  app_tasks: ['id'],
  app_vacations: ['id'],
  areas: ['id'],
  bank_accounts: ['id'],
  bank_sync_runs: ['id'],
  bank_transactions: ['id'],
  blank_color_tuning: ['color_id'],
  bot_telegram_bindings: ['telegram_chat_id'],
  bug_reports: ['id'],
  cases: ['id'],
  certificate_redemptions: ['id'],
  certificates: ['id'],
  china_orders: ['id'],
  china_purchases: ['id'],
  consent_logs: ['id'],
  email_subscribers: ['id'],
  employees: ['id'],
  faq: ['id'],
  finance_accounts: ['id'],
  finance_categories: ['id'],
  finance_counterparties: ['id'],
  finance_directions: ['id'],
  finance_manual_decisions: ['id'],
  finance_rules: ['id'],
  finance_sources: ['id'],
  finance_transaction_links: ['id'],
  finance_transactions: ['id'],
  fintablo_imports: ['id'],
  form_submissions: ['id'],
  hw_blanks: ['id'],
  legacy_finance_import_runs: ['id'],
  legacy_finance_transactions: ['id'],
  marketplace_sets: ['id'],
  message_templates: ['id'],
  molds: ['id'],
  notification_log: ['id'],
  order_factuals: ['id'],
  order_items: ['id'],
  order_shipments: ['id'],
  order_timeline: ['id'],
  orders: ['id'],
  page_content: ['id'],
  pkg_blanks: ['id'],
  product_templates: ['id'],
  products: ['id'],
  projects: ['id'],
  promo_codes: ['id'],
  promo_redemptions: ['id'],
  return_requests: ['id'],
  settings: ['key'],
  shipments: ['id'],
  shop_orders: ['id'],
  site_settings: ['key'],
  task_checklist_items: ['id'],
  task_comments: ['id'],
  task_notification_events: ['id'],
  task_watchers: ['task_id', 'user_id'],
  tasks: ['id'],
  time_entries: ['id'],
  warehouse_history: ['id'],
  warehouse_items: ['id'],
  warehouse_reservations: ['id'],
  work_activity: ['id'],
  work_assets: ['id'],
  work_templates: ['id'],
});

export function primaryKeyFor(table) {
  return COMPAT_PRIMARY_KEYS[table] || null;
}
