import express from 'express';
import cookieParser from 'cookie-parser';
import healthRoute from './routes/health.js';
import authRoute from './routes/auth.js';
import employeesRoute from './routes/employees.js';
import warehouseRoute from './routes/warehouse.js';
import shipmentsRoute from './routes/shipments.js';
import chinaRoute from './routes/china.js';
import moldsRoute from './routes/molds.js';
import blanksRoute from './routes/blanks.js';
import colorsRoute from './routes/colors.js';
import marketplacesRoute from './routes/marketplaces.js';
import bugsRoute from './routes/bugs.js';
import calcRoute from './routes/calc.js';
import templatesRoute from './routes/templates.js';
import productionRoute from './routes/production.js';
import indirectRoute from './routes/indirect.js';
import ordersRoute from './routes/orders.js';
import areasRoute from './routes/areas.js';
import projectsRoute from './routes/projects.js';
import tasksRoute from './routes/tasks.js';
import workEventsRoute from './routes/work-events.js';
import internalRoute from './routes/internal.js';
import botRoute from './routes/bot.js';
import { selectelUrlSigningMiddleware } from './s3.js';

export function createServer() {
  const app = express();
  app.set('trust proxy', 1);
  app.use(express.json({ limit: '5mb' }));
  app.use(cookieParser());
  app.use(selectelUrlSigningMiddleware());
  app.use('/api', healthRoute);
  app.use('/api/auth', authRoute);
  app.use('/api/employees', employeesRoute);
  app.use('/api/warehouse', warehouseRoute);
  app.use('/api/shipments', shipmentsRoute);
  app.use('/api/china', chinaRoute);
  app.use('/api/molds', moldsRoute);
  app.use('/api/blanks', blanksRoute);
  app.use('/api/colors', colorsRoute);
  app.use('/api/marketplaces', marketplacesRoute);
  app.use('/api/bugs', bugsRoute);
  app.use('/api/calc', calcRoute);
  app.use('/api/templates', templatesRoute);
  app.use('/api/production', productionRoute);
  app.use('/api/indirect-costs', indirectRoute);
  app.use('/api/orders', ordersRoute);
  app.use('/api/areas', areasRoute);
  app.use('/api/projects', projectsRoute);
  app.use('/api/tasks', tasksRoute);
  app.use('/api/work', workEventsRoute);
  app.use('/api/internal', internalRoute);
  app.use('/api/bot', botRoute);
  return app;
}
