-- 003_warehouse.sql
-- Warehouse redesign: normalized items, canonical reservations, and canonical
-- movement history. This intentionally does not mirror the legacy cache shape.

CREATE TABLE IF NOT EXISTS warehouse_items (
    id              BIGINT PRIMARY KEY,
    sku             TEXT,
    name            TEXT NOT NULL,
    category        TEXT,
    qty             NUMERIC NOT NULL DEFAULT 0 CHECK (qty >= 0),
    unit            TEXT,
    min_qty         NUMERIC,
    last_price      NUMERIC,
    last_currency   TEXT,
    notes           TEXT,
    linked_order_id BIGINT,
    photo_url       TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_warehouse_items_sku ON warehouse_items(LOWER(sku));
CREATE INDEX IF NOT EXISTS idx_warehouse_items_category ON warehouse_items(category);

CREATE TABLE IF NOT EXISTS warehouse_reservations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id         BIGINT NOT NULL REFERENCES warehouse_items(id) ON DELETE CASCADE,
    -- orders arrive in Block 9. Keep this as a raw BIGINT for now, then add the
    -- FK with ON DELETE CASCADE when the orders table exists.
    order_id        BIGINT,
    qty             NUMERIC NOT NULL CHECK (qty > 0),
    source          TEXT NOT NULL DEFAULT 'order' CHECK (source IN ('order','manual')),
    status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','released','consumed')),
    note            TEXT,
    actor_user_id   INTEGER REFERENCES auth_users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    consumed_at     TIMESTAMPTZ,
    released_at     TIMESTAMPTZ,
    CONSTRAINT reservation_order_has_order_id
        CHECK ((source = 'order' AND order_id IS NOT NULL) OR source != 'order'),
    CONSTRAINT reservation_consumed_has_timestamp
        CHECK ((status = 'consumed' AND consumed_at IS NOT NULL) OR status != 'consumed'),
    CONSTRAINT reservation_released_has_timestamp
        CHECK ((status = 'released' AND released_at IS NOT NULL) OR status != 'released')
);
CREATE INDEX IF NOT EXISTS idx_reservations_item ON warehouse_reservations(item_id);
CREATE INDEX IF NOT EXISTS idx_reservations_order ON warehouse_reservations(order_id) WHERE order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_reservations_status ON warehouse_reservations(status);
CREATE INDEX IF NOT EXISTS idx_reservations_active_by_item ON warehouse_reservations(item_id) WHERE status = 'active';

CREATE TABLE IF NOT EXISTS warehouse_history (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id            BIGINT REFERENCES warehouse_items(id) ON DELETE SET NULL,
    type               TEXT NOT NULL CHECK (type IN ('receipt','consume','inventory_audit','manual_edit','return')),
    qty_before         NUMERIC,
    qty_after          NUMERIC,
    qty_change         NUMERIC NOT NULL,
    order_id           BIGINT,
    shipment_id        BIGINT,
    mold_id            BIGINT,
    marketplace_set_id BIGINT,
    audit_id           BIGINT,
    actor_user_id      INTEGER REFERENCES auth_users(id) ON DELETE SET NULL,
    actor_name         TEXT,
    note               TEXT,
    details            JSONB DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT history_receipt_positive CHECK (type != 'receipt' OR qty_change > 0),
    CONSTRAINT history_consume_negative CHECK (type != 'consume' OR qty_change < 0),
    CONSTRAINT history_return_positive CHECK (type != 'return' OR qty_change > 0)
);
CREATE INDEX IF NOT EXISTS idx_history_item ON warehouse_history(item_id);
CREATE INDEX IF NOT EXISTS idx_history_created ON warehouse_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_history_type ON warehouse_history(type);

INSERT INTO app_meta (id, version) VALUES (1, '003-warehouse')
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();
