-- 004_shipments_china.sql
-- Shipments + China purchases/catalog. Receipt operations write warehouse
-- history(type='receipt') and increment warehouse_items through the API.

CREATE TABLE IF NOT EXISTS shipments (
    id              BIGINT PRIMARY KEY,
    name            TEXT NOT NULL,
    source          TEXT,
    status          TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','in_transit','received','cancelled')),
    expected_date   DATE,
    received_at     TIMESTAMPTZ,
    total_cost      NUMERIC,
    currency        TEXT,
    note            TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_shipments_status ON shipments(status);
CREATE INDEX IF NOT EXISTS idx_shipments_expected_date ON shipments(expected_date);
CREATE INDEX IF NOT EXISTS idx_shipments_source ON shipments(source);

CREATE TABLE IF NOT EXISTS shipment_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id       BIGINT NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
    warehouse_item_id BIGINT REFERENCES warehouse_items(id) ON DELETE SET NULL,
    name              TEXT NOT NULL,
    qty               NUMERIC NOT NULL CHECK (qty > 0),
    unit_price        NUMERIC,
    currency          TEXT,
    received_qty      NUMERIC,
    extras            JSONB DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_shipment_items_shipment ON shipment_items(shipment_id);
CREATE INDEX IF NOT EXISTS idx_shipment_items_warehouse_item ON shipment_items(warehouse_item_id);

CREATE TABLE IF NOT EXISTS china_purchases (
    id              BIGINT PRIMARY KEY,
    title           TEXT,
    supplier        TEXT,
    order_url       TEXT,
    status          TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','paid','in_transit','arrived','received','cancelled')),
    paid_amount     NUMERIC,
    paid_currency   TEXT,
    paid_at         TIMESTAMPTZ,
    arrived_at      TIMESTAMPTZ,
    shipment_id     BIGINT REFERENCES shipments(id) ON DELETE SET NULL,
    note            TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_china_purchases_status ON china_purchases(status);
CREATE INDEX IF NOT EXISTS idx_china_purchases_shipment ON china_purchases(shipment_id);

CREATE TABLE IF NOT EXISTS china_purchase_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id       BIGINT NOT NULL REFERENCES china_purchases(id) ON DELETE CASCADE,
    warehouse_item_id BIGINT REFERENCES warehouse_items(id) ON DELETE SET NULL,
    name              TEXT NOT NULL,
    qty               NUMERIC NOT NULL CHECK (qty > 0),
    unit_price        NUMERIC,
    currency          TEXT,
    extras            JSONB DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_china_purchase_items_purchase ON china_purchase_items(purchase_id);
CREATE INDEX IF NOT EXISTS idx_china_purchase_items_warehouse_item ON china_purchase_items(warehouse_item_id);

CREATE TABLE IF NOT EXISTS china_catalog (
    id              BIGINT PRIMARY KEY,
    name            TEXT NOT NULL,
    sku             TEXT,
    description     TEXT,
    photo_url       TEXT,
    last_price      NUMERIC,
    last_currency   TEXT,
    supplier        TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_china_catalog_sku ON china_catalog(LOWER(sku));
CREATE INDEX IF NOT EXISTS idx_china_catalog_name ON china_catalog(LOWER(name));

INSERT INTO app_meta (id, version) VALUES (1, '004-shipments-china')
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();
