-- 005_molds_blanks.sql
-- Molds, blanks, colors, and marketplace sets. Mold and marketplace usage
-- consume warehouse stock directly through API transactions; they do not create
-- warehouse reservations.

CREATE TABLE IF NOT EXISTS molds (
    id              BIGINT PRIMARY KEY,
    name            TEXT NOT NULL,
    type            TEXT,
    status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','retired','broken')),
    capacity        INTEGER,
    usage_count     INTEGER NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
    usage_limit     INTEGER,
    photo_url       TEXT,
    note            TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_molds_status ON molds(status);
CREATE INDEX IF NOT EXISTS idx_molds_name ON molds(LOWER(name));

CREATE TABLE IF NOT EXISTS mold_hardware (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mold_id           BIGINT NOT NULL REFERENCES molds(id) ON DELETE CASCADE,
    warehouse_item_id BIGINT REFERENCES warehouse_items(id) ON DELETE SET NULL,
    qty_per_use       NUMERIC NOT NULL CHECK (qty_per_use > 0),
    note              TEXT,
    extras            JSONB DEFAULT '{}'::jsonb,
    UNIQUE (mold_id, warehouse_item_id)
);
CREATE INDEX IF NOT EXISTS idx_mold_hardware_mold ON mold_hardware(mold_id);
CREATE INDEX IF NOT EXISTS idx_mold_hardware_warehouse_item ON mold_hardware(warehouse_item_id);

CREATE TABLE IF NOT EXISTS mold_usage_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mold_id         BIGINT NOT NULL REFERENCES molds(id) ON DELETE CASCADE,
    units           INTEGER NOT NULL CHECK (units > 0),
    order_id        BIGINT,
    operator_name   TEXT,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mold_usage_log_mold ON mold_usage_log(mold_id);
CREATE INDEX IF NOT EXISTS idx_mold_usage_log_created ON mold_usage_log(created_at DESC);

CREATE TABLE IF NOT EXISTS hw_blanks (
    id              BIGINT PRIMARY KEY,
    sku             TEXT,
    name            TEXT NOT NULL,
    category        TEXT,
    weight          NUMERIC,
    last_price      NUMERIC,
    last_currency   TEXT,
    photo_url       TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_hw_blanks_sku ON hw_blanks(LOWER(sku));
CREATE INDEX IF NOT EXISTS idx_hw_blanks_name ON hw_blanks(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_hw_blanks_category ON hw_blanks(category);

CREATE TABLE IF NOT EXISTS pkg_blanks (
    id              BIGINT PRIMARY KEY,
    sku             TEXT,
    name            TEXT NOT NULL,
    category        TEXT,
    last_price      NUMERIC,
    last_currency   TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pkg_blanks_sku ON pkg_blanks(LOWER(sku));
CREATE INDEX IF NOT EXISTS idx_pkg_blanks_name ON pkg_blanks(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_pkg_blanks_category ON pkg_blanks(category);

CREATE TABLE IF NOT EXISTS app_colors (
    id              BIGINT PRIMARY KEY,
    name            TEXT NOT NULL,
    hex             TEXT,
    category        TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_app_colors_name ON app_colors(LOWER(name));
CREATE INDEX IF NOT EXISTS idx_app_colors_category ON app_colors(category);

CREATE TABLE IF NOT EXISTS marketplace_sets (
    id              BIGINT PRIMARY KEY,
    name            TEXT NOT NULL,
    marketplace     TEXT,
    sku             TEXT,
    price           NUMERIC,
    currency        TEXT,
    composition     JSONB DEFAULT '[]'::jsonb,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT marketplace_sets_composition_array CHECK (jsonb_typeof(composition) = 'array')
);
CREATE INDEX IF NOT EXISTS idx_marketplace_sets_marketplace ON marketplace_sets(marketplace);
CREATE INDEX IF NOT EXISTS idx_marketplace_sets_active ON marketplace_sets(is_active);
CREATE INDEX IF NOT EXISTS idx_marketplace_sets_sku ON marketplace_sets(LOWER(sku));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'warehouse_history_mold_id_fkey'
    ) THEN
        ALTER TABLE warehouse_history
            ADD CONSTRAINT warehouse_history_mold_id_fkey
            FOREIGN KEY (mold_id) REFERENCES molds(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'warehouse_history_marketplace_set_id_fkey'
    ) THEN
        ALTER TABLE warehouse_history
            ADD CONSTRAINT warehouse_history_marketplace_set_id_fkey
            FOREIGN KEY (marketplace_set_id) REFERENCES marketplace_sets(id) ON DELETE SET NULL;
    END IF;
END $$;

INSERT INTO app_meta (id, version) VALUES (1, '005-molds-blanks')
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();
