-- 006_bug_reports.sql
-- Bug reports and attachment metadata. Attachment bytes live in private
-- Selectel Object Storage and are exposed through short-lived signed URLs.

CREATE TABLE IF NOT EXISTS bug_reports (
    id              BIGINT PRIMARY KEY,
    title           TEXT NOT NULL,
    description     TEXT,
    severity        TEXT CHECK (severity IN ('low','medium','high','critical')),
    status          TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','fixed','wontfix','duplicate')),
    page            TEXT,
    reporter_email  TEXT,
    reporter_name   TEXT,
    assignee_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fixed_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_bug_reports_status ON bug_reports(status);
CREATE INDEX IF NOT EXISTS idx_bug_reports_severity ON bug_reports(severity);
CREATE INDEX IF NOT EXISTS idx_bug_reports_page ON bug_reports(page);
CREATE INDEX IF NOT EXISTS idx_bug_reports_assignee ON bug_reports(assignee_id);
CREATE INDEX IF NOT EXISTS idx_bug_reports_created ON bug_reports(created_at DESC);

CREATE TABLE IF NOT EXISTS bug_attachments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bug_id          BIGINT NOT NULL REFERENCES bug_reports(id) ON DELETE CASCADE,
    filename        TEXT NOT NULL,
    mime_type       TEXT,
    size_bytes      BIGINT,
    storage_key     TEXT NOT NULL,
    uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_bug_attachments_bug ON bug_attachments(bug_id);
CREATE INDEX IF NOT EXISTS idx_bug_attachments_storage_key ON bug_attachments(storage_key);

INSERT INTO app_meta (id, version) VALUES (1, '006-bugs')
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();
