-- 007_production.sql
-- Product templates, production calendar/plan, and indirect costs.

CREATE TABLE IF NOT EXISTS product_templates (
    id              BIGINT PRIMARY KEY,
    name            TEXT NOT NULL,
    category        TEXT,
    data            JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_product_templates_active ON product_templates(is_active);
CREATE INDEX IF NOT EXISTS idx_product_templates_category ON product_templates(category);
CREATE INDEX IF NOT EXISTS idx_product_templates_name ON product_templates(LOWER(name));

CREATE TABLE IF NOT EXISTS production_calendar_days (
    date            DATE PRIMARY KEY,
    is_working      BOOLEAN NOT NULL,
    hours           NUMERIC NOT NULL DEFAULT 8 CHECK (hours >= 0),
    note            TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_production_calendar_working ON production_calendar_days(is_working);

CREATE TABLE IF NOT EXISTS production_plan_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    order_id        BIGINT,
    item_name       TEXT,
    qty             NUMERIC CHECK (qty IS NULL OR qty >= 0),
    hours_planned   NUMERIC CHECK (hours_planned IS NULL OR hours_planned >= 0),
    operator_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    status          TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned','in_progress','done','cancelled')),
    position        INTEGER NOT NULL DEFAULT 100,
    note            TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_production_plan_date ON production_plan_entries(date);
CREATE INDEX IF NOT EXISTS idx_production_plan_order ON production_plan_entries(order_id);
CREATE INDEX IF NOT EXISTS idx_production_plan_operator ON production_plan_entries(operator_id);
CREATE INDEX IF NOT EXISTS idx_production_plan_date_position ON production_plan_entries(date, position, id);

CREATE TABLE IF NOT EXISTS indirect_costs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_year     INTEGER NOT NULL,
    period_month    INTEGER NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    category        TEXT NOT NULL,
    amount          NUMERIC NOT NULL CHECK (amount >= 0),
    currency        TEXT NOT NULL DEFAULT 'RUB',
    note            TEXT,
    extras          JSONB DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (period_year, period_month, category)
);
CREATE INDEX IF NOT EXISTS idx_indirect_costs_period ON indirect_costs(period_year, period_month);

INSERT INTO app_meta (id, version) VALUES (1, '007-production')
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();
