-- 008_orders.sql
-- Orders, order items, factuals, and order-status audit trail.

CREATE TABLE IF NOT EXISTS orders (
    id                  BIGINT PRIMARY KEY,
    order_name          TEXT,
    client_name         TEXT,
    client_email        TEXT,
    client_phone        TEXT,
    status              TEXT NOT NULL DEFAULT 'draft' CHECK (status IN (
        'draft','quoted','approved','in_production','ready','shipped','closed','cancelled'
    )),
    deadline            DATE,
    deadline_start      DATE,
    manager_id          BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    quantity            INTEGER,
    total_revenue       NUMERIC,
    total_cost          NUMERIC,
    total_margin        NUMERIC,
    margin_percent      NUMERIC,
    total_hours_plan    NUMERIC,
    production_hours_plastic    NUMERIC,
    production_hours_packaging  NUMERIC,
    production_hours_hardware   NUMERIC,
    calculator_data     JSONB,
    extras              JSONB DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_deadline ON orders(deadline);
CREATE INDEX IF NOT EXISTS idx_orders_client ON orders(LOWER(client_name));
CREATE INDEX IF NOT EXISTS idx_orders_manager ON orders(manager_id);
CREATE INDEX IF NOT EXISTS idx_orders_updated ON orders(updated_at DESC);

CREATE TABLE IF NOT EXISTS order_items (
    id              BIGINT PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    type            TEXT,
    name            TEXT,
    qty             NUMERIC,
    unit_price      NUMERIC,
    line_total      NUMERIC,
    item_data       JSONB DEFAULT '{}'::jsonb,
    position        INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_position ON order_items(order_id, position, id);

CREATE TABLE IF NOT EXISTS order_factuals (
    id              BIGINT PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    factual_data    JSONB NOT NULL,
    actual_revenue  NUMERIC,
    actual_cost     NUMERIC,
    actual_margin   NUMERIC,
    actual_margin_percent NUMERIC,
    closed_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (order_id)
);
CREATE INDEX IF NOT EXISTS idx_order_factuals_order ON order_factuals(order_id);

CREATE TABLE IF NOT EXISTS order_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    from_status     TEXT,
    to_status       TEXT NOT NULL,
    actor_user_id   INTEGER REFERENCES auth_users(id) ON DELETE SET NULL,
    actor_name      TEXT,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_order_status_history_order ON order_status_history(order_id, created_at DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'warehouse_reservations_order_id_fkey'
    ) THEN
        ALTER TABLE warehouse_reservations
            ADD CONSTRAINT warehouse_reservations_order_id_fkey
            FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
            NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'warehouse_history_order_id_fkey'
    ) THEN
        ALTER TABLE warehouse_history
            ADD CONSTRAINT warehouse_history_order_id_fkey
            FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL
            NOT VALID;
    END IF;
END $$;

INSERT INTO app_meta (id, version) VALUES (1, '008-orders')
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();
