-- 013_bot_state.sql
-- Telegram bot state moves from local files to Postgres.

ALTER TABLE employees ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'Europe/Moscow';

CREATE TABLE IF NOT EXISTS bot_telegram_bindings (
    telegram_chat_id  BIGINT PRIMARY KEY,
    telegram_username TEXT,
    employee_id       BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    bound_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active         BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_bot_binding_active_employee
    ON bot_telegram_bindings(employee_id) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_bot_binding_employee ON bot_telegram_bindings(employee_id);

CREATE TABLE IF NOT EXISTS bot_conversation_state (
    chat_id    BIGINT PRIMARY KEY REFERENCES bot_telegram_bindings(telegram_chat_id) ON DELETE CASCADE,
    flow       TEXT,
    step       TEXT,
    draft      JSONB NOT NULL DEFAULT '{}'::jsonb,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_bot_state_expires ON bot_conversation_state(expires_at);

CREATE TABLE IF NOT EXISTS bot_message_inbox (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id               BIGINT NOT NULL,
    telegram_message_id   BIGINT NOT NULL,
    text                  TEXT,
    payload               JSONB NOT NULL DEFAULT '{}'::jsonb,
    received_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at          TIMESTAMPTZ,
    processing_started_at TIMESTAMPTZ,
    error                 TEXT,
    UNIQUE (chat_id, telegram_message_id)
);
CREATE INDEX IF NOT EXISTS idx_bot_inbox_unprocessed
    ON bot_message_inbox(chat_id, received_at) WHERE processed_at IS NULL;

CREATE TABLE IF NOT EXISTS bot_tokens (
    token        TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    role         TEXT NOT NULL DEFAULT 'bot' CHECK (role IN ('bot','admin')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);

INSERT INTO app_meta (id, version) VALUES (1, '013-bot-state')
ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version, applied_at = NOW();
